# -*- coding: utf-8 -*-
# g6: Saim-Hann 赛姆-汉灵族 + Sororitas 战斗修女 中译生成脚本
# 术语权威: Warpforge部队卡片/_tmp_rulebook_terms.json (官方规则书提取) + 规则书中文翻译md
# 歧义文本已用卡面图 vision 核对(N处修正见报告)
import json

T = {
# ============ Saim-Hann 灵族 单位 ============
"Autarch": "总督",
"Death Spinner Warp Spider": "死亡纺锤扭曲蜘蛛",
"Dire Avenger Exarch": "复仇者长老",
"Dire Avenger": "复仇者",
"Farseer": "先知",
"Fire Dragon": "火龙",
"Guardian Defender": "防卫守护者",
"Howling Banshee Exarch": "嚎叫女妖长老",
"Howling Banshee": "嚎叫女妖",
"Orian Laratharjos": "奥里安·拉拉萨约斯",
"Ranger": "游侠",
"Spiritseer Qelenaris": "灵先知·奎莱纳里斯",
"Spiritseer": "灵先知",
"Storm Guardian": "风暴守护者",
"Striking Scorpion Exarch": "突击蝎子长老",
"Striking Scorpion": "突击蝎子",
"Swooping Hawk Exarch": "俯冲猎鹰长老",
"Swooping Hawk": "俯冲猎鹰",
"Vengeful Wraithblade": "复仇幽刃",
"Veteran Guardian": "老兵守护者",
"Warlock": "术士",
"Warp Spider Exarch": "扭曲蜘蛛长老",
"Warp Spider": "扭曲蜘蛛",
"Weapons Platform": "武器平台",
"Winged Autarch": "有翼总督",
"Witchblade Warlock": "巫刃术士",
"Wraithblade": "幽刃",
"Wraithguard": "幽卫",
"Yrlla the Huntress": "女猎手伊尔拉",
"Avatar of Khaine": "凯恩化身",
"Blackout": "黑幕",
"Infinity Circuit Overload": "无限回路过载",
"Normal Conditions": "正常状态",
"Webway Rift": "网道裂隙",
# ============ Saim-Hann 战术 ============
"Aerial Dominion": "空中霸权",
"Ahnakh-Yth Shrine": "阿纳赫-伊斯圣殿",
"Aspect Shrine": "支派圣殿",
"Banshee Mask": "女妖面具",
"Bladestorm": "剑刃风暴",
"Cosmic Serpent": "宇宙巨蛇",
"Craftworld Convergence": "方舟世界汇聚",
"Dance of Death": "死亡之舞",
"Deadly Ambush": "致命伏击",
"Devoted of Khaine": "凯恩信徒",
"Eldritch Storm": "秘术风暴",
"Empyric Ambush": "灵能伏击",
"Evasive Manoeuvre": "规避机动",
"Fate Inescapable": "宿命难逃",
"Fire and Fade": "打了就跑",
"Flickerjump": "闪烁跳跃",
"Forewarned": "预警",
"Graceful Avoidance": "灵巧规避",
"Hosts of the Dead": "亡者军团",
"Infinity Circuit": "无限回路",
"Inspiring Legacy": "激励传承",
"Nightshade Interceptors": "夜影拦截者",
"Path of Command": "统御之道",
"Path of the Seer": "先知之道",
"Path of the Warrior": "战士之道",
"Reclaim the Stars": "夺回群星",
"Skyborne Deployment": "空降部署",
"Storm of Silence": "寂静风暴",
"Sudden Assault": "突袭",
"Wailing Doom": "恸哭毁灭",
"Webway Entrance": "网道入口",
"Webway Gate": "网道之门",
"Webway Incursion": "网道入侵",
"Whirling Death": "回旋之死",
"Wild Host": "狂野宿主",
"Will of Asuryan": "阿斯尤扬之意志",
"Witchfire": "巫火",
"Wrath of Khaine": "凯恩之怒",
# ============ Saim-Hann 载具 ============
"Bright Lance Vyper": "亮枪蝰蛇",
"Crimson Hunter": "猩红猎手",
"Falcon": "猎鹰",
"Farseer Skyrunner": "先知天行者",
"Fire prism": "火焰棱镜",
"Hemlock Wraithfighter": "铁杉魂飞者",
"Hornet": "大黄蜂",
"Night Spinner": "夜纺者",
"Nuadhu Fireheart": "努阿杜·火心",
"Shining Spear Exarch": "闪耀之矛长老",
"Shining Spear": "闪耀之矛",
"Shroud Runner": "隐匿行者",
"Vyper": "蝰蛇",
"War Walker": "战争行者",
"Warlock Skyrunner": "术士天行者",
"Wave Serpent": "波浪蛇",
"Windrider": "风行者",
"Wraithknight": "幽骑士",
"Wraithlord": "幽尊",
# ============ Saim-Hann 督军 ============
"Anvirr Keltoc": "安维尔·凯尔托克",
"Eliac Zephyrblade": "伊利亚克·泽菲刃",
"Medreyal Ghaelyn": "梅德雷亚尔·盖林",
"Jain Zar": "杰因·扎尔",
"Lhykhis": "莱基斯",
# ============ 战斗修女 单位 ============
"Adelaide the Serene": "宁静的阿德莱德",
"Aestred-Thurga": "艾斯特雷德-瑟加",
"Amalia Novena": "阿玛莉亚·诺维娜",
"Arco-Flagellant": "电鞭苦修者",
"Armorium Cherub": "军械库小天使",
"Battle Sister Gunner": "战斗修女枪手",
"Battle Sister": "战斗修女",
"Canoness": "教长",
"Celestian Sacresant": "天界修女圣卫",
"Celestian Superior": "天界修女长",
"Celestian": "天界修女",
"Crusader": "十字军战士",
"Death Cult Assassin": "死亡教派刺客",
"Dialogus": "执事",
"Dominion Superior": "多米尼恩修女长",
"Dominion": "多米尼恩修女",
"Ephrael Stern": "埃弗拉尔·斯特恩",
"Hospitaller": "医疗修女",
"Imagifier": "圣像师",
"Ministorum Priest": "国教牧师",
"Missionary": "传教士",
"Preacher": "布道者",
"Retributor": "惩戒修女",
"Sacred Rose Sister": "圣玫瑰修女",
"Saint Celestine": "圣塞莱斯廷",
"Seraphim": "炽天使",
"Simulacrum Bearer": "圣像持有者",
"Simulacrum Imperialis": "帝皇圣像",
"Sister Dogmata": "教义修女",
"Sister Novitiate": "见习修女",
"Sister Superior": "修女长",
"Sisters Repentia": "忏悔修女",
"Triumph of Saint Katherine": "圣凯瑟琳凯旋",
"Zephyrim Superior": "泽菲里姆修女长",
"Zephyrim": "泽菲里姆修女",
# ============ 战斗修女 战术/防御 ============
"Beacon of Faith": "信仰灯塔",
"Blade of Faith": "信仰之刃",
"Cleansing Flames": "净化之焰",
"Conviction of Faith": "坚定信仰",
"Daemonbreaker": "破魔者",
"Defenders of the Faith": "信仰捍卫者",
"Devout Serenity": "虔诚宁静",
"Devout Warriors": "虔诚战士",
"Disrupted Sanctuary": "受扰圣所",
"Divine Intervention": "神圣干预",
"Emperor's Judgement": "帝皇的审判",
"Fiery Conviction": "炽热信念",
"Furious Reprisal": "狂怒报复",
"Fury of the Righteous": "义人之怒",
"Guidance of the Saints": "圣徒指引",
"Hallowed Martyrs": "圣洁殉道者",
"Holy Fire": "圣火",
"Hymn of Battle": "战斗圣歌",
"Imperial Creed": "帝国信条",
"Inspiring Oratory": "激励演说",
"Lead the Righteous": "引领义人",
"Miraculous Feat": "奇迹壮举",
"Normal": "普通",
"Prayer": "祷文",
"Purgator Mirabilis": "奇迹涤罪者",
"Raging Storm": "狂暴风暴",
"Relics of Saint Katherine": "圣凯瑟琳圣物",
"Righteous Repugnance": "义愤",
"Rite of Restoration": "复原仪式",
"Sacred Altar": "圣坛",
"Sacred Rose": "圣玫瑰",
"Shrine Bombardement": "圣殿轰击",
"Shrineworld": "圣殿世界",
"Slay the Heretic": "斩杀异端",
"Spirit of the Martyr": "殉道者之灵",
"Trial of Suffering": "苦难试炼",
# ============ 战斗修女 载具 ============
"Castigator": "惩戒者",
"Exorcist": "驱魔者",
"Immolator": "焚化者",
"Mortifier": "苦修机",
"Paragon Warsuit": "典范战甲",
"Penitent Engine": "忏悔引擎",
"Sororitas Rhino": "修女犀牛",
# ============ 战斗修女 督军 ============
"Celestian Sacresant Aveline": "天界修女圣卫·阿芙琳",
"Erika Luminas": "埃丽卡·卢米纳斯",
"Junith Eruita": "朱妮丝·埃鲁伊塔",
"Morvenn Vahl": "莫文·瓦尔",
"Moment of Grace": "恩典时刻",
}

D = {
# ---- Saim-Hann 单位 ----
"Autarch": "给予你的所有部队 +1 近战、+1 远程和 +1 生命",
"Death Spinner Warp Spider": "路标石。潜行 (1)。获得侧翼。",
"Dire Avenger Exarch": "路标石。星镖 3。集结：所有敌人失去潜行和伪装。",
"Dire Avenger": "路标石。星镖 2",
"Farseer": "当你收集灵魂石时，获得护盾。①从你的牌库中选择 1 张牌并抽到它",
"Fire Dragon": "路标石。爆裂 4",
"Guardian Defender": "路标石。星镖 2",
"Howling Banshee Exarch": "路标石。伪装。猛击：给予你的单位 +1 近战攻击",
"Howling Banshee": "集结：眩晕一个敌人",
"Orian Laratharjos": "路标石。潜行。当友方单位失去潜行时，本回合给予它星镖 1。天赋：闪烁跳跃",
"Ranger": "路标石。潜行。狙击",
"Spiritseer Qelenaris": "当你收集灵魂石时，额外获得 2 颗灵魂石",
"Spiritseer": "部署 1 个幽卫",
"Storm Guardian": "星镖 1",
"Striking Scorpion Exarch": "路标石。潜行。星镖 4",
"Striking Scorpion": "路标石。潜行。星镖 2",
"Swooping Hawk Exarch": "集结：给予 1 个单位先锋直到你的下个回合",
"Swooping Hawk": "①：获得 +1 远程攻击和侧翼",
"Vengeful Wraithblade": "②：获得护甲 2 和侧翼",
"Veteran Guardian": "路标石。星镖 1",
"Warlock": "给予你的所有部队 +1 远程攻击和 +1 生命",
"Warp Spider Exarch": "当你收集灵魂石时，获得 +1 近战、+1 远程和潜行。",
"Warp Spider": "猛击：将此部队返回你的手牌",
"Weapons Platform": "",
"Winged Autarch": "你的其他飞行单位获得 +2 近战和 +2 远程攻击",
"Witchblade Warlock": "路标石。天赋：巫火",
"Wraithblade": "获得护甲 2",
"Wraithguard": "获得 +2 远程攻击和 +2 生命",
"Yrlla the Huntress": "当敌人受到眩晕时，对其造成 3 点伤害",
"Avatar of Khaine": "护甲 2。获得爆裂 6 和伪装。天赋：凯恩之怒。",
"Blackout": "",
"Infinity Circuit Overload": "",
"Normal Conditions": "",
"Webway Rift": "",
# ---- Saim-Hann 战术 ----
"Aerial Dominion": "对 1 个随机敌人造成 3 点伤害。每有 1 个友方载具便重复此效果",
"Ahnakh-Yth Shrine": "给予 1 个友方部队星镖 1。①在你的手牌中生成 1 张阿纳赫-伊斯圣殿的复制",
"Aspect Shrine": "获得 2 颗灵魂石",
"Banshee Mask": "对 1 个敌人造成 3 点伤害并使其眩晕",
"Bladestorm": "本回合给予你的单位星镖 2",
"Cosmic Serpent": "触发你所有部队需要灵魂石的能力。②重复此效果",
"Craftworld Convergence": "选择一项：获得 2 颗灵魂石；部署 1 个老兵守护者；或抽 2 张牌",
"Dance of Death": "给予 1 个友方单位星镖 2",
"Deadly Ambush": "给予 1 个友方部队侧翼，或眩晕 1 个敌方部队",
"Devoted of Khaine": "给予你的部队 +1 近战攻击。①重复此效果",
"Eldritch Storm": "对所有敌人造成 1-3 点伤害。\n②重复此效果",
"Empyric Ambush": "临时。造成 2 点伤害。若目标死亡，给予 1 个随机友方步兵潜行。",
"Evasive Manoeuvre": "为 1 个友方单位治疗 5 点生命并给予其伪装",
"Fate Inescapable": "若你控制 1 个具有潜行的单位，此卡费用 -1。给予 1 个敌方部队脆弱 2",
"Fire and Fade": "将 1 个友方部队返回你的手牌\n使其费用 -2",
"Flickerjump": "临时。本回合给予 1 个友方步兵星镖 1 和飞行。若其有潜行，给予它侧翼",
"Forewarned": "本回合给予 1 个友方单位 +3 攻击和 +3 护甲。①同时给予它护盾",
"Graceful Avoidance": "给予 1 个友方部队「💀反噬：返回你的手牌」",
"Hosts of the Dead": "部署 1 个幽卫。消耗你所有的灵魂石。每消耗 1 颗，部署 1 个幽卫。",
"Infinity Circuit": "获得 5 颗灵魂石",
"Inspiring Legacy": "本回合给予 1 个友方单位星镖 2",
"Nightshade Interceptors": "②给予你的载具 +1 远程攻击和 +2 生命",
"Path of Command": "临时。部署 1 个风暴守护者",
"Path of the Seer": "临时。选择你手牌中的 1 张牌并将其放回牌库。抽 1 张牌。获得 ①。",
"Path of the Warrior": "临时。本回合给予你的单位星镖 1",
"Reclaim the Stars": "抽 5 张牌。⑤使其费用 -5",
"Skyborne Deployment": "部署 2 个风暴守护者",
"Storm of Silence": "你的督军本回合获得 +2 [生命]。①[能量]：眩晕 1 个随机敌方部队",
"Sudden Assault": "你的每个单位对 1 个随机敌人造成等同于其星镖值的伤害",
"Wailing Doom": "对 1 个敌人造成 8 点伤害。②对目标相邻单位造成 4 点伤害",
"Webway Entrance": "选择 1 个赛姆-汉步兵并将其置入手牌",
"Webway Gate": "从你的牌库中选择 1 张部队牌并抽到它。①其费用 -2",
"Webway Incursion": "给予 1 个友方部队潜行",
"Whirling Death": "对 1 个部队造成 5 点伤害。若目标死亡，对相邻单位造成 2 点伤害",
"Wild Host": "在你的手牌中生成 2 个随机赛姆-汉载具。其费用 -1",
"Will of Asuryan": "给予 1 个友方部队先锋。\n①抽 1 张牌",
"Witchfire": "造成 1-3 点伤害。\n①重复此效果",
"Wrath of Khaine": "给予你的单位 +2 近战和 +2 远程攻击。②重复此效果",
# ---- Saim-Hann 载具 ----
"Bright Lance Vyper": "当你触发灵魂石能力时，获得 +1 攻击。",
"Crimson Hunter": "集结：对 1 个敌人造成 3 点伤害。若其有飞行，改为造成 6 点伤害",
"Falcon": "飞行。星镖 3",
"Farseer Skyrunner": "选择敌方手牌中的 1 张牌并将其洗入其牌库",
"Fire prism": "造成 3 点伤害。若目标有护甲，改为造成 8 点伤害",
"Hemlock Wraithfighter": "③：获得爆裂 5",
"Hornet": "③：获得迅捷",
"Night Spinner": "爆裂 3",
"Nuadhu Fireheart": "猛击：本回合给予相邻部队无敌",
"Shining Spear Exarch": "飞行。侧翼。当你部署 1 个载具时，给予它星镖 1",
"Shining Spear": "①：本回合获得星镖 2",
"Shroud Runner": "飞行。侧翼。狙击",
"Vyper": "星镖 3",
"War Walker": "护甲。爆裂",
"Warlock Skyrunner": "飞行。当你收集灵魂石时，对 1 个随机敌人造成 2-3 点伤害",
"Wave Serpent": "飞行。天赋：空降部署",
"Windrider": "飞行。侧翼。星镖 2",
"Wraithknight": "获得 [无敌] 无敌直到你的下个回合",
"Wraithlord": "③：获得 +4 近战、+4 远程和 +2 生命",
# ---- Saim-Hann 督军 ----
"Anvirr Keltoc": "天赋：先知之道",
"Eliac Zephyrblade": "天赋：战士之道",
"Medreyal Ghaelyn": "天赋：统御之道",
"Jain Zar": "当敌人受到眩晕时，对其造成 1 点伤害。天赋：寂静风暴",
"Lhykhis": "潜行。天赋：灵能伏击",
# ---- 战斗修女 单位 ----
"Adelaide the Serene": "6：获得侧翼和护盾。集结：若你的能量少于 6 点，每有 1 个敌方单位便获得 1 点能量。",
"Aestred-Thurga": "当友方单位祈祷时，给予它护盾。祈祷：给予你的单位 +1 生命",
"Amalia Novena": "集结：对 1 个敌方部队造成等同于你信仰值的伤害",
"Arco-Flagellant": "忏悔：对所有其他单位造成 1 点伤害",
"Armorium Cherub": "飞行。集结：本回合给予 1 个友方单位 +2 近战攻击。在你的回合开始时，获得 1 ☀并返回你的手牌。",
"Battle Sister Gunner": "祈祷：对 1 个敌人造成 2 点伤害",
"Battle Sister": "祈祷：获得 +1 近战和 +1 远程并治疗 1 点生命",
"Canoness": "2 ☀：获得护甲 1。\n4 ☀：获得 +2 ⚔ 和 +2 🔫。",
"Celestian Sacresant": "祈祷：为 1 个友方单位治疗 3 点生命",
"Celestian Superior": "祈祷：部署 1 个天界修女。6☀：部署 1 个天界修女",
"Celestian": "祈祷：获得护盾",
"Crusader": "3 ☀：获得 +1 近战攻击和护甲 2",
"Death Cult Assassin": "忏悔：对 1 个随机敌人造成 2 点伤害",
"Dialogus": "祈祷：给予 1 个友方单位护盾",
"Dominion Superior": "集结：造成 1 点伤害。2 ☀：额外造成 1 点伤害",
"Dominion": "爆裂 2",
"Ephrael Stern": "祈祷：造成 2-3 点伤害。若目标死亡，获得 1 ☀。",
"Hospitaller": "祈祷：为 1 个友方单位治疗 3 点生命",
"Imagifier": "祈祷：给予 1 个友方部队 +1 近战、+1 远程和侧翼",
"Ministorum Priest": "祈祷：本回合给予 1 个友方单位 +3 近战攻击",
"Missionary": "猛击：获得 +1 ☀。天赋：战斗圣歌",
"Preacher": "5 ☀：获得护盾",
"Retributor": "1 ☀：对 1 个随机敌人造成 3 点伤害",
"Sacred Rose Sister": "2 ☀：获得 +1 近战和 +1 远程。4 ☀：获得 +1 生命。祈祷：获得护盾。",
"Saint Celestine": "集结：获得无敌直到你的下个回合",
"Seraphim": "3 ☀：获得 +1 远程攻击和 +1 生命",
"Simulacrum Bearer": "给予你的部队 +1 [护甲]，本回合同样给予你的督军",
"Simulacrum Imperialis": "祈祷：给予所有友方单位 +1 护甲和 +1 攻击。",
"Sister Dogmata": "集结：造成 1 点伤害。若目标死亡或是友方单位，获得 1 ☀。",
"Sister Novitiate": "3 ☀：获得 +1 生命。\n祈祷：部署 1 个见习修女",
"Sister Superior": "祈祷：造成 1 点伤害",
"Sisters Repentia": "当此单位击杀 1 个敌人时，获得 1 ☀。忏悔：获得 +2 [护甲]。",
"Triumph of Saint Katherine": "护甲 2。当友方单位祈祷时，给予它护甲 1。祈祷：对 1 个敌人造成等同于你信仰值的伤害",
"Zephyrim Superior": "祈祷：抽 1 张部队牌",
"Zephyrim": "飞行。侧翼",
# ---- 战斗修女 战术/防御 ----
"Beacon of Faith": "给予你的单位 +2 生命。\n4 ☀：额外给予 +1 生命。\n7 ☀：同时给予它们 +1 攻击和 +1 武器。",
"Blade of Faith": "对 1 个敌方部队造成 3 点伤害。4 ☀：重复此效果",
"Cleansing Flames": "对 1 个敌人及其相邻单位造成 3 点伤害",
"Conviction of Faith": "所有友方单位直到你的下个回合获得护甲 2，并治疗 2 点生命",
"Daemonbreaker": "直到你的下个回合给予你的督军 +1 [攻击]、爆裂 1 和护盾。8 [能量]：使其永久生效",
"Defenders of the Faith": "每有 1 个敌方单位，部署 1 个战斗修女",
"Devout Serenity": "给予你的单位护盾。每个正在祈祷的友方单位治疗 3 点生命",
"Devout Warriors": "抽 1 张部队牌。2 ☀：再抽 1 张部队牌",
"Disrupted Sanctuary": "",
"Divine Intervention": "摧毁攻击力最高的敌方部队。8 ☀：摧毁所有敌方部队",
"Emperor's Judgement": "摧毁 1 个敌方部队。恢复等同于你信仰值的能量",
"Fiery Conviction": "直到你的下个回合给予你的单位 +2 [力量]。4 [能量]：额外给予 +1 [力量]",
"Furious Reprisal": "给予 1 个友方部队侧翼。若其受伤，本回合给予它爆裂 3",
"Fury of the Righteous": "临时。\n造成 1 点伤害。\n4 ☀：额外造成 2 点伤害",
"Guidance of the Saints": "你的下 1 个步兵费用 -2",
"Hallowed Martyrs": "你的督军获得「忏悔：对 2 个随机敌方部队各造成 1 点伤害」",
"Holy Fire": "本回合给予你的督军 +2 力量，并给予相邻部队 +1 力量。获得 1 ☀。",
"Hymn of Battle": "选择一项：获得 1 点能量；抽 1 张牌；或部署 1 个十字军战士",
"Imperial Creed": "眩晕 3 个随机敌人。\n4 ☀：恢复 3 点能量",
"Inspiring Oratory": "给予 1 个友方部队护盾和先锋",
"Lead the Righteous": "部署 1 个战斗修女。\n8 ☀：额外部署 1 个战斗修女",
"Miraculous Feat": "本回合给予 1 个友方单位 [无敌] 无敌。6 [能量]：将效果延长到你的下个回合",
"Normal": "",
"Prayer": "给予 1 个友方单位护盾。若该单位具有祈祷，获得 1 ☀。",
"Purgator Mirabilis": "",
"Raging Storm": "",
"Relics of Saint Katherine": "获得 3 ☀。12 ☀：抽 3 张牌",
"Righteous Repugnance": "本回合给予你的单位 +1 攻击和 +1 生命。4 能量：改为给予 +2 攻击和 +2 生命，并治疗 1 点生命",
"Rite of Restoration": "选择 1 个自你的上个回合以来死亡的友方部队并部署它",
"Sacred Altar": "给予 1 个友方单位 🛡护盾。获得 1 ☀。",
"Sacred Rose": "部署 2 个圣玫瑰修女。6 ☀：给予它们侧翼",
"Shrine Bombardement": "",
"Shrineworld": "抽 3 张牌。每抽到 1 张部队牌，获得 1 ☀。",
"Slay the Heretic": "",
"Spirit of the Martyr": "对所有单位造成 1 点伤害。若有任何部队死亡，重复此效果",
"Trial of Suffering": "对 1 个友方部队造成 1 点伤害并给予它护甲 1。2 ☀：改为给予它护甲 2",
# ---- 战斗修女 载具 ----
"Castigator": "护甲 1。当友方单位祈祷时，对 1 个随机敌人造成 2 点伤害",
"Exorcist": "对所有敌人造成 5 点伤害",
"Immolator": "祈祷：对 1 个敌人及其相邻单位造成 3 点伤害",
"Mortifier": "忏悔：对敌方督军造成 2 点伤害",
"Paragon Warsuit": "护甲 1。当你获得信仰时，对敌方督军造成 4 点伤害。\n6 ☀：获得先锋",
"Penitent Engine": "忏悔：获得侧翼和爆裂 2",
"Sororitas Rhino": "在你的回合结束时，若有友方单位正在祈祷，部署 1 个圣玫瑰修女",
# ---- 战斗修女 督军 ----
"Celestian Sacresant Aveline": "祈祷：给予 1 个友方部队 +1 近战和 +1 远程。天赋：破魔者",
"Erika Luminas": "祈祷：给予 1 个友方单位 +1 生命。天赋：义人之怒",
"Junith Eruita": "祈祷：为 1 个友方单位治疗 1 点生命。天赋：引领义人",
"Morvenn Vahl": "祈祷：造成 1 点伤害。\n天赋：义愤",
"Moment of Grace": "本回合给予 1 个友方单位 +2 近战和 +2 远程攻击。5 ☀：抽 1 张牌",
}

src = json.load(open(r'd:/2/Warpforge_tools/scripts/_tmp_slices/g6.json', encoding='utf-8'))
out = {}
missing_n, missing_d = [], []
for c in src:
    nm = c['name']
    if nm not in T:
        missing_n.append(nm); continue
    if nm not in D:
        missing_d.append(nm); continue
    out[nm] = {"n": T[nm], "d": D[nm]}

if missing_n or missing_d:
    print("MISSING:", missing_n, missing_d)
else:
    with open(r'd:/2/Warpforge_tools/scripts/_tmp_zhcards_g6.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=0)
    print("written", len(out))
