#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 _tmp_zhcards_g5.json — g5 (Sautekh + Astra Militarum) 卡牌中译"""
import json, sys

SRC = "d:/2/Warpforge_tools/scripts/_tmp_slices/g5.json"
OUT = "d:/2/Warpforge_tools/scripts/_tmp_zhcards_g5.json"

T = {
"Ursula Creed": ("克里德", "天赋：传奇司令官。职责：部署一个震荡突击兵。"),
"Minka Lesk": ("明卡·莱斯克", "友方步兵的费用减少 1 点。"),
"Defence Batteries": ("防御炮组", "对 3 个随机敌人各造成 1 点伤害。"),
"Munitorum Supplies": ("军需补给", "选择一张星界军部队牌并置入手牌。其费用减少 2 点。"),
"Timely Reinforcements": ("及时增援", "部署一个震荡突击兵。"),
"Astropath": ("星语者", "职责：抽一张战术，并使其费用减少 2 点。"),
"Attilan Rough Rider": ("阿提拉莽骑兵", "集结：若你不控制其他部队，本回合获得嗜血。"),
"Bullgryn Bone\u2019ead": ("布尔格伦骨脑", "爆破 2。"),
"Cadian Castellan": ("卡迪亚守备官", "使手牌中的一个友方部队费用减少 1 点。"),
"Cadian Medic": ("卡迪亚医疗兵", "为一个随机友方单位治疗 1 点。"),
"Cadian Standard Bearer": ("卡迪亚旗手", "集结：部署一个震荡突击兵。职责：本回合给予你的单位 +2 [攻击]。"),
"Commissar": ("政委", "当友方部队触发职责时，给予其装甲 1。"),
"Faeburn Vanquisher": ("法伯恩·歼灭者", "选择你手牌中的一张部队牌。其费用减少 1 点。"),
"Flamer Trooper": ("喷火兵", "爆破 1。职责：对所有敌人造成 2-3 点伤害。"),
"Kasrkin": ("卡斯金", "团：对一个随机敌人造成 1 点伤害。若其死亡，抽一张卡。"),
"Maelon Dhrost": ("梅隆·德罗斯特", "抽一张战术。你手牌中的战术费用减少 4 点。"),
"Master of Ordnance": ("军械大师", "在你的回合结束时，每有一个在场友方载具，对一个随机敌人造成 3 点伤害。"),
"Medic Scion": ("医护圣选兵", "集结：为一个友方单位治疗 2 点。职责：部署一个本回合阵亡的随机友方步兵。"),
"Nork Deddog": ("诺克·德多格", "天赋：著名保镖。"),
"Ogryn": ("奥格林", "先锋。"),
"Primaris Psyker": ("常备灵能者", "护盾。职责：对一个敌人造成 2-3 点伤害，或给予一个友方单位护盾。"),
"Ratling": ("鼠人", "团：对一个随机敌方部队造成 1 点伤害。"),
"Shock Trooper Sgt": ("震荡突击兵军士", "部署一个震荡突击兵。"),
"Shock Trooper": ("震荡突击兵", "造成 1 点伤害。"),
"Tech-Priest Enginseer": ("机械神甫机务师", "团：为一个友方载具治疗 2 点。职责：你手牌与卡组中的所有载具费用减少 1 点。"),
"Tempestor Sergeant": ("暴风军士长", "团：给予一个随机友方部队 +1 攻击。职责：给予所有友方步兵 +1 生命。"),
"Tempestus Aquilon": ("暴风阿奎隆", "飞行。斩杀：对敌方督军造成 3 点伤害。"),
"Tempestus Scion": ("暴风圣选兵", "伪装。职责：对一个敌人造成 2 点伤害。若其为部队，使其眩晕。"),
"Vitus Gryf": ("维图斯·格里夫", "拥有飞行的友方部队获得侧翼。猛击：部署一个暴风阿奎隆。"),
"Vox Operator": ("通讯兵", "当你部署一个载具时，给予其侧翼。"),
"Dawn Attack": ("黎明突袭", ""),
"Factories Overdrive": ("工厂超载", ""),
"Normal": ("正常", ""),
"Planetary invasion": ("行星入侵", ""),
"Armoured Lightning": ("装甲闪电", "部署 3 个暴风圣选兵并给予其先锋。若你控制一个载具，则再给予它们装甲 1。"),
"Armoured Squadron": ("装甲中队", "选择一张星界军载具牌并置入手牌。其费用减少 2 点。"),
"Artillery Strike": ("炮火打击", "对 2 个随机敌人各造成 3-5 点伤害。"),
"At All Costs": ("不惜一切", "抽 3 张卡。若你的督军生命值不高于 10，这些卡的费用减少 4 点。"),
"Born Soldier": ("天生士兵", "造成 1 点伤害。若目标死亡，抽一张卡。"),
"Cadia Stands": ("卡迪亚屹立", "本场战斗剩余时间内：在你的回合开始时，部署一个震荡突击兵。"),
"Cadian Honour": ("卡迪亚荣誉", "给予你的部队 +1，并重置其职责能力。"),
"Efficiency and Excellence": ("效率与卓越", "临时。造成 1 点伤害。若目标死亡，抽一张卡。"),
"Forged Killers": ("锻造杀手", "给予一个友方部队及其相邻部队 +2 [攻击]。"),
"Full Throttle": ("全速前进", "本回合你打出的下一张载具费用减少 2 点。"),
"Godspear Warhead": ("神矛弹头", "对所有敌方部队造成 10 点伤害。"),
"High Command": ("最高指挥部", "补满你的所有能量。"),
"Lead by Example": ("以身作则", "临时。给予一个友方单位 +2 生命，并重置其职责能力。"),
"Legendary Commandant": ("传奇司令官", "临时。选择一张星界军战术牌并加入你的手牌。"),
"Mechanised Infantry": ("机械化步兵", "部署 3 个震荡突击兵。每当你部署一个载具时，此牌费用减少 1 点。"),
"Move! Move! Move!": ("前进！前进！前进！", "给予你的所有步兵部队侧翼。"),
"Pinning Fire": ("压制火力", "对一个敌人造成 2 点伤害，并使其眩晕。"),
"Press the Attack": ("主动出击", "重置你所有单位的职责能力。抽一张部队牌。"),
"Recon Operation": ("侦察行动", "所有敌人失去潜行和伪装。若没有敌人受影响，抽 2 张卡。"),
"Regimental Doctrine": ("团队教义", "为你所有单位治疗 2 点，并触发其团能力。"),
"Renowned Bodyguard": ("著名保镖", "你的督军获得无敌，持续到你的下个回合。"),
"Righteous Gaze": ("正义凝视", ""),
"Shock Troops": ("突击部队", "每有一个在场友方单位，对一个随机敌人造成 1 点伤害。"),
"Siege Warfare": ("围城战", "从你的卡组中抽两张载具并部署它们。"),
"Summary Execution": ("即决处决", "消灭一个友方部队和一个随机敌方部队。"),
"Thermal Weaponry": ("热能武器", "给予一个友方部队爆破 3。若其为载具，则同时给予其装甲 1。"),
"Thunderous Charge": ("雷霆冲锋", "给予一个友方部队 +2 [攻击]、+2 [装甲] 和震荡。"),
"Valkyrie Drop": ("女武神空降", "对一个敌人造成 3 点伤害。若目标死亡，部署一个暴风圣选兵。"),
"Vengeance for Cadia": ("为卡迪亚复仇", "直到你的下个回合，给予你的单位 +2 [远程]。每当一个友方部队死亡时，此牌费用减少 1 点。"),
"Aquilon Servo-Sentry": ("阿奎隆伺服哨戒", "在每个回合结束时，对一个随机敌人造成 1 点伤害。"),
"Armoured Sentinel": ("装甲哨兵", "装甲 1。团：获得 +1。"),
"Autocannon Squad": ("自动炮小队", "团：获得 +1。"),
"Baneblade Tank": ("毒刃战车", "装甲 2。相邻单位获得装甲 1。职责：造成 8 点伤害。"),
"Basilisk": ("巴西利斯克", "远射。爆破 3。"),
"Bombast Field Gun": ("邦巴斯特野战炮", "对一个敌人及其相邻单位造成 3-5 点伤害。"),
"Chimera": ("奇美拉", "友方步兵部队获得装甲 1。职责：部署 2 个震荡突击兵。"),
"Hydra": ("九头蛇", "团：对一个随机拥有飞行的敌人造成 4 点伤害。"),
"Leman Russ Vanquisher": ("黎曼鲁斯·歼灭者", "装甲 1。职责：造成 8 点伤害。若目标拥有装甲，则改为造成 12 点伤害。"),
"Leman Russ": ("黎曼鲁斯", "对一个随机敌人造成 2 点伤害。"),
"Manticore": ("曼提柯尔", "爆破 2。职责：对所有敌人造成 2-4 点伤害。"),
"Rogal Dorn Tank": ("罗加·多恩坦克", "团：本回合给予你的单位 +1 [攻击]。"),
"Scout Sentinel": ("侦察哨兵", "抽 2 张卡。"),
"Taurox Prime": ("陶洛克精英装甲车", "装甲 1。职责：部署 2 个暴风圣选兵并给予其侧翼。"),
"Taurox": ("陶洛克装甲车", "团：在你的手牌中生成一张震荡突击兵。"),
"Valkyrie": ("瓦尔基里", "职责：对所有敌人造成 2 点伤害。每有一个因此死亡的敌人，部署一个震荡突击兵。"),
"Commissar Elan": ("政委·埃兰", "天赋：以身作则。职责：给予一个友方步兵侧翼。"),
"Hektor Thenmann": ("赫克托·滕曼", "对一个敌人造成 2 点伤害并使其眩晕。天赋：效率与卓越。"),
"Lord Solar Leontus": ("太阳领主莱昂图斯", "天赋：统帅。职责：造成 3 点伤害。"),
"Ophydian Destroyer": ("奥菲迪安毁灭者", "再生 2。巧技：获得潜行。"),
"Canoptek Plasmacyte": ("冥府质体", "当你部署一个拥有毁灭者的部队时，给予其再生 1。"),
"Canoptek Scarab": ("冥府圣甲虫", "巧技：部署一个冥府圣甲虫。"),
"Canoptek Spyder": ("冥府蜘蛛", "再生 1。巧技：部署一个冥府圣甲虫。"),
"Canoptek Wraith": ("冥府幽灵", "此部队攻击时可以无视拥有先锋的敌方单位。"),
"Chronomancer": ("时相术士", "在你的回合结束时，复生一个随机友方残骸。天赋：复生。"),
"Cryptothrall": ("墓穴仆役", "残骸。先锋。"),
"Damaged Hexmark": ("受损六印毁灭者", "攻击生命值最低的随机敌人。"),
"Damaged Plasmacyte": ("受损冥府质体", "相邻单位获得再生 2。"),
"Deathmark": ("死印", "集结：若你不控制其他部队，获得潜行。"),
"Flayed One": ("剥皮者", "被复生时，获得迅捷。"),
"Flayed Ones Pack": ("剥皮者兽群", "部署一个剥皮者。"),
"Gauss Blaster Immortal": ("高斯冲击枪不朽者", "残骸。再生 2。"),
"Gauss Reaper Warrior": ("高斯收割者战士", "被复生时，获得 +2 远程攻击和 +2 生命。"),
"Hexmark Destroyer": ("六印毁灭者", "对 4 个随机敌人各造成 1 点伤害。"),
"Immortals Phalanx": ("不朽者方阵", "被复生时，部署此部队的一个复制。"),
"Lokhust Destroyer": ("洛库斯特毁灭者", "当另一个部队死亡时，对一个随机敌人造成 1 点伤害。"),
"Lokhust Heavy Destroyer": ("洛库斯特重型毁灭者", "被复生时，对一个随机敌人造成 3 点伤害。"),
"Lokhust Lord": ("洛库斯特领主", "反噬：在你的手牌中生成一张复活宝珠。"),
"Lychguard": ("圣卫兵", "残骸。装甲 2。先锋。"),
"Necron Lord": ("死灵领主", "残骸。再生 2。天赋：不屈意志。"),
"Necron Warrior": ("死灵战士", "残骸。先锋。"),
"Plasmancer": ("等离子术士", "巧技：对一个随机敌人造成 3 点伤害。"),
"Psychomancer": ("心灵术士", "集结：使一个敌人眩晕。"),
"Royal Warden": ("皇家典狱官", "集结：对一个敌人造成 3 点伤害。"),
"Scarab Swarm": ("圣甲虫虫群", "再生 3。此部队的近战值始终等于其生命值。"),
"Skorpekh Destroyer": ("斯科尔佩赫毁灭者", "残骸。毁灭者。侧翼。"),
"Skorpekh Lord": ("斯科尔佩赫领主", "当一个敌人死亡时，获得 +1 近战和 +1 远程攻击。"),
"Technomancer": ("技术术士", "巧技：复生一个随机友方残骸。"),
"Tesla Carbine Immortal": ("特斯拉卡宾枪不朽者", "对一个随机敌人造成 1 点伤害。"),
"Triarch Praetorian": ("三王禁卫", "残骸。先锋。"),
"Vargard Obyron": ("瓦加德·奥比伦", "装甲 2。任何以你的督军为目标的攻击改为以该部队为目标。"),
"Canoptek Reanimator": ("冥府复生者", "天赋：复生。集结：复生一个友方残骸。"),
"Earthquake": ("地震", ""),
"Immortal Beams": ("不朽光束", ""),
"Normal Conditions": ("正常条件", ""),
"Solar Storm": ("太阳风暴", ""),
"Annihilation Command": ("歼灭指令", ""),
"Awakened Dynasty": ("觉醒王朝", "抽 2 张卡。每抽到一张部队牌，在你的手牌中生成一张复生协议。"),
"Awakening Obelisk": ("苏醒方尖碑", "对一个敌人造成 1 点伤害。若目标死亡，将一张歼灭协议加入你的手牌。"),
"Conquering Tyrant": ("征服暴君", "为你的督军治疗 5 点，并给予其 +2 近战攻击。"),
"Curse of the Phaeron": ("法老诅咒", "给予所有敌方部队易伤 2。"),
"Dimensional Breach": ("次元裂隙", "部署 3 个随机 2 费索泰克部队。"),
"Dimensional Corridor": ("次元走廊", "从你的卡组中选择一张部队牌。抽取它，并在你的手牌中生成其复制。"),
"Disentegration Capacitors": ("解离电容", ""),
"Disruption Blades": ("扰乱之刃", "本回合给予你的单位 +1 [攻击]；若其为毁灭者，则给予 +3 [攻击]。"),
"Divination Menhir": ("占卜石柱", "你的下一张战术费用减少 1。"),
"Extermination Protocols": ("歼灭协议", "造成 2 点伤害。"),
"Hardwired Destruction": ("硬接线毁灭", "直到你的下个回合，给予一个友方单位 +1 [攻击] 和 +1 [生命]。若其为 [毁灭者]，则直到你的下个回合给予其装甲 1。"),
"Hyperlogical Strategist": ("超逻辑战略家", "选择一张索泰克战术牌并置入手牌。"),
"Immortal Pride": ("不朽之傲", "给予你所有单位装甲 1。本场战斗剩余时间内：你的督军天赋费用减少 1 点。"),
"Implacable Conqueror": ("无情征服者", "你卡组中所有部队牌的费用减少 2 点。抽一张部队牌。"),
"Indomitable Will": ("不屈意志", "选择一张霸主威能并置入手牌。"),
"Inescapable Retribution": ("无法逃脱的惩罚", "部署 2 个墓刃。"),
"Lord of the Storm": ("风暴领主", "临时。对一个敌人造成 1 点伤害，并为你的督军治疗 1 点。若目标死亡，在你的手牌中生成一张风暴领主。"),
"Master Chronomancer": ("时相大师", "从你的卡组中选择一张卡，置于你的卡组顶部。"),
"Methodical Destruction": ("有条不紊的毁灭", "消灭一个敌方部队，并对相邻单位造成 2-3 点伤害。"),
"Particle Whip": ("粒子鞭", "临时。对一个敌人造成 8 点伤害，并对其相邻单位造成 3 点伤害。"),
"Protection Protocol": ("保护协议", "给予一个友方部队 +3 生命和先锋，或复生一个友方残骸。"),
"Reanimate": ("复生", "复生一个友方残骸。"),
"Reanimation Protocol": ("复生协议", "复生一个友方残骸。"),
"Reconstitution Protocols": ("重构协议", "选择一张本场战斗中阵亡的友方部队牌，置入手牌。"),
"Relentless Advance": ("无情推进", "为你的单位治疗 3 点。"),
"Relentless March": ("无情进军", "部署一个死灵战士。"),
"Resurrection Orb": ("复活宝珠", "复生所有友方残骸。"),
"Resurrection Vault": ("复活圣库", "复生一个友方残骸，并给予其 +1 生命。"),
"Scythe Assault": ("镰刀突击", "对所有敌人造成 2-3 点伤害。"),
"Self-Destruction": ("自我毁灭", "消灭所有友方冥府圣甲虫。每消灭一个，对一个随机敌人造成 3 点伤害。"),
"Solar Pulse": ("太阳脉冲", "使所有敌人失明，并使其失去潜行和伪装。"),
"Spyder Nest": ("蜘蛛巢", "部署 2 个冥府圣甲虫。"),
"Tomb World": ("墓穴世界", "部署至多 5 个本场战斗中阵亡的友方步兵部队。"),
"Nemesor Zahndrekh": ("内默萨·赞德雷克", "相邻的残骸不会在你的回合结束时消失。天赋：无情进军。"),
"Diviner": ("占卜师", "每当你复生一个残骸时，治疗 1 点。"),
"Ramatekh The Cruel": ("残忍者拉玛泰克", "毁灭者。你的其他毁灭者获得 +1 [攻击]。天赋：硬接线毁灭。"),
"Lord Commander": ("统帅", "临时。直到你的下个回合，给予你的单位 +1/+1。"),
"Undying Legions": ("不朽军团", "本场战斗剩余时间内：每当友方部队变为残骸时，其获得护盾。给予你的督军护盾。"),
"Awakened Obelisk": ("觉醒方尖碑", "对一个敌人造成 1 点伤害。若目标死亡，将一张歼灭协议加入你的手牌。"),
"Annihilation Barge": ("歼灭驳船", "巧技：对生命值最低的敌人造成 3 点伤害。"),
"Command Barge": ("指挥驳船", "飞行。天赋：复生。"),
"Doom Scythe": ("末日镰刀", "飞行。侧翼。"),
"Doomstalker": ("末日行者", "当一个敌人攻击时，对其造成 2-3 点伤害。"),
"Ghost Ark": ("幽灵方舟", "天赋：复生。巧技：部署一个死灵战士。"),
"Monolith": ("独石碑", "装甲 3。天赋：粒子鞭。巧技：部署一个死灵战士。"),
"Night Scythe": ("夜镰", "若你不控制其他部队，部署一个死灵战士。"),
"Tomb Blade": ("墓刃", "残骸。飞行。侧翼。"),
"Triarch Stalker": ("三王猎手", "你的其他单位获得 +2 远程攻击。"),
}

SKIP = {"HB", "stormlord"}  # 均指引同卡：Imotekh the Stormlord 别名卡（ocrName 佐证），非正式卡名

src = json.load(open(SRC, encoding="utf-8"))
names = [e["name"] for e in src]
out = {}
for n in names:
    if n in SKIP:
        continue
    if n not in T:
        print("MISSING:", n)
        sys.exit(1)
    out[n] = {"n": T[n][0], "d": T[n][1]}

# 检查输入中是否真正出现 SKIP 名
for n in SKIP:
    assert n in names, f"{n} not in input!"

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=0)
print("total input:", len(names), "| skipped:", len(SKIP), "| output:", len(out))
